### PR TITLE
faust2w64vst exporter

### PR DESCRIPTION
**Pull request by jatinchowdhury18**
I've been using this script to generate 64-bit VSTs on my Windows machine.

I need a little bit of help on line 29 figuring out the correct mingw prefix for the mingw64 compiler on Mac/Linux.

Thanks!

### CODE REVIEW

**Comment by sletz** [comment]
Greta ! @dfober do you have an idea how to solve the "line 29" issue?

**Comment by jatinchowdhury18** [comment]
I made an educated guess at the correct compiler prefix based off the [`faust2w64max6`](https://github.com/grame-cncm/faust/blob/8eb19155c72ccac1aa33f19d4f21ebafb67787f5/tools/faust2appls/faust2w64max6#L43) script. Hopefully this will work!

**Comment by sletz** [comment]
Your script is now on the online compiler. Can you test that it works? On which host?

**Comment by jatinchowdhury18** [comment]
Awesome, just tested with the MoogVCF and ClarinetMIDI example scripts, and everything worked as expected. For the moment I'm only able to test on Ableton Live 10.

**Pull request merged**
