### PR TITLE
Update to Web Components v2

### PR DESCRIPTION
**Pull request by Korilakkuma**
This PR will update to Web Components v2.
In concrete,

- [Custom Elements](https://www.webcomponents.org/specs#the-custom-elements-specification)
- [Shadow DOM](https://www.webcomponents.org/specs#the-shadow-dom-specification)
- [ES Module](https://www.webcomponents.org/specs#the-es-module-specification)
- [HTML Template](https://www.webcomponents.org/specs#the-html-template-specification)

### CODE REVIEW

**Comment by sletz** [comment]
`This PR is Work in Progress because of faust is not defined ...` do you want me to merge this PR right now? Or do you prefer continuing the work until it actually works ?

**Comment by Korilakkuma** [comment]
I prefer continuing the work until it actually works. But, it seems that `faust` is not defined in `libfaust-wasm.js`. So, this PR intended for help me ...

**Comment by sletz** [comment]
- look at https://github.com/grame-cncm/faust/tree/master-dev/architecture/webaudio
- the  webaudio-wasm-wrapper.js file has to be imported 
- look also at https://github.com/grame-cncm/faust/blob/master-dev/architecture/webaudio/faustlive-wasm.html 

```
 // 'faust_module' global is defined in webaudio-wasm-wrapper.js file, 'onRuntimeInitialized' will be called when code is ready
 faust_module['onRuntimeInitialized'] = init;
```

**Comment by sletz** [comment]
Any progress here ?

**Comment by Korilakkuma** [comment]
This PR is completed. But, AppVeyor build failed ...

**Comment by sletz** [comment]
This issue was solved on master-dev, you'll probably have to rebase your PR and submit it again.

**Comment by sletz** [comment]
Merged, thanks !

**Pull request merged**
