### PR TITLE
Update wasm standalone wrapper and its html

### PR DESCRIPTION
**Pull request by Fr0stbyteR**
Clean up and upgrade of actual codes using ES6, fix issues #292 #291

### CODE REVIEW

**Comment by sletz** [comment]
Thanks. I tried the code but something seems to be broken. You should  generate pages with all the possible options and check that everything still works, like:

```
faust2webaudiowasm clarinetMIDI.dsp
faust2webaudiowasm -poly clarinetMIDI.dsp
faust2webaudiowasm -poly  -effect effect.dsp  clarinetMIDI.dsp
faust2webaudiowasm -poly  -effect euro clarinetMIDIWithAutoEffect.dsp
...
```

**Comment by Fr0stbyteR** [comment]
The issue is probably the static property inside a class is not standardized in some browsers, I just fixed it.

> Thanks. I tried the code but something seems to be broken. You should generate pages with all the possible options and check that everything still works, like:
> 
> ```
> faust2webaudiowasm clarinetMIDI.dsp
> faust2webaudiowasm -poly clarinetMIDI.dsp
> faust2webaudiowasm -poly  -effect effect.dsp  clarinetMIDI.dsp
> faust2webaudiowasm -poly  -effect euro clarinetMIDIWithAutoEffect.dsp
> ...
> ```
> and load the generated pages.
> 
> Plaise also they `faust2wasm` scripts with the different options. Possibly you'll have to craate some test HTML pages.

**Comment by Fr0stbyteR** [comment]
> This is not a typo ! sp.outs is the result of the mixing process, and has to be processed my sp.effect. So the same sp.outs buffer is used for in and out. This has to be reverted and you can add a command to make things more clear.

I realized that immediately... it's reverted

**Comment by Fr0stbyteR** [comment]
I'm wondering why these codes are not there in poly AudioWorkletProcessor (in process method): 
```
// Update controls (possibly needed for sample accurate control)
var params = Object.entries(parameters);
for (var i = 0; i < params.length; i++) {
    this.HEAPF32[this.pathTable[params[i][0]] >> 2] = params[i][1][0];
}
```
Apparently it doesn't work in poly mode for moment, do I need to make it work ? 

PS: is https://github.com/grame-cncm/fausteditorweb the right repo to go for improve the editor

**Comment by sletz** [comment]
I finally merged the PR in` git merge --squash` mode in https://github.com/grame-cncm/faust/commit/16e8b6821cf143fd2b465f100228dd3f35f94165. 

I see that effect mode is broken, for instance:
 `faust2webaudiowasm -poly -worklet  -effect freeverb.dsp  clarinetMIDI.dsp`
 `faust2webaudiowasm -poly  -effect auto clarinetMIDIFreeverb.dsp`

Can you have a look? You'll probable have to prepare a fresh PR when the fix is ready.

**Comment by Fr0stbyteR** [comment]
> I finally merged the PR in` git merge --squash` mode in [16e8b68](https://github.com/grame-cncm/faust/commit/16e8b6821cf143fd2b465f100228dd3f35f94165).
> 
> I see that effect mode is broken, for instance:
> `faust2webaudiowasm -poly -worklet -effect freeverb.dsp clarinetMIDI.dsp`
> `faust2webaudiowasm -poly -effect auto clarinetMIDIFreeverb.dsp`
> 
> Can you have a look? You'll probable have to prepare a fresh PR when the fix is ready.



> I finally merged the PR in` git merge --squash` mode in [16e8b68](https://github.com/grame-cncm/faust/commit/16e8b6821cf143fd2b465f100228dd3f35f94165).
> 
> I see that effect mode is broken, for instance:
> `faust2webaudiowasm -poly -worklet -effect freeverb.dsp clarinetMIDI.dsp`
> `faust2webaudiowasm -poly -effect auto clarinetMIDIFreeverb.dsp`
> 
> Can you have a look? You'll probable have to prepare a fresh PR when the fix is ready.

I cannot reproduce your issue with these commands with Chrome 72, Safari 12 and Firefox 65. In fact, I haven't modified the files for -worklet mode, they are original ones. 
What exactly the errors ?

**Comment by sletz** [comment]
Sorry, it is broken in ScriptProcessor mode, two with :  
`faust2webaudiowasm -poly  -effect freeverb.dsp clarinetMIDI.dsp`
`faust2webaudiowasm -poly -effect auto clarinetMIDIFreeverb.dsp`

**Comment by Fr0stbyteR** [comment]
> Sorry, it is broken in ScriptProcessor mode, two with :
> `faust2webaudiowasm -poly -effect freeverb.dsp clarinetMIDI.dsp`
> `faust2webaudiowasm -poly -effect auto clarinetMIDIFreeverb.dsp`

Can I take a look at your errors in browser console ?

**Comment by sletz** [comment]
I don't have errors, just the fact the effect does not apply on the sound anymore...

**Comment by Fr0stbyteR** [comment]
> I don't have errors, just the fact the effect does not apply on the sound anymore...

Just fixed, my bad, there was another instantiateStreaming.

**Comment by sletz** [comment]
Thanks, taken using git cherry pick.

**Pull request closed without merging**
