### PR TITLE
rust: provide a compute_arrays function

### PR DESCRIPTION
**Pull request by crop2000**
The benefit of using arrays as function arguments is that they fail compilation if a wrong length array is provided.
When the compute_arrays function is used then we have one less possible panic.

### CODE REVIEW

**Comment by sletz** [comment]
Be sure that to test the Rust backend with `make rust` in tests/impulse-tests folder.

**Comment by crop2000** [comment]
@sletz after fixing the error introduced by me some tests are failing, which are also failing on master-dev.

**Comment by sletz** [comment]
> @sletz after fixing the error introduced by me some tests are failing, which are also failing on master-dev.

Which ones ?

**Comment by crop2000** [comment]
```
crop@yoga ~/p/r/f/f/t/impulse-tests (master-dev)> make rust
make -f Make.rust FAUSTOPTIONS="-I dsp -double"
make[1]: Entering directory '/home/crop/projects/rust/forks/faust/tests/impulse-tests'
mkdir -p ir/rust
../../build/bin/faust -lang rust -I dsp -double -i -A ../../architecture -a archs/rust/architecture.rs dsp/vcf_wah_pedals.dsp -o archs/rust/src/bin/vcf_wah_pedals.rs
#cd archs/rust/ && cargo run --bin vcf_wah_pedals ../../ir/rust/vcf_wah_pedals.ir
cd archs/rust/ && cargo run --release --bin vcf_wah_pedals ../../ir/rust/vcf_wah_pedals.ir
   Compiling faust-impulse-test v0.1.0 (/home/crop/projects/rust/forks/faust/tests/impulse-tests/archs/rust)
error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3205:91
     |
3205 | ...0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} e...
     |       -----------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--------------------------------------------------------------
     |       |                |
     |       |                expected `()`, found `f64`
     |       expected this to be `()`
     |
help: consider using a semicolon here
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44};} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                       +
help: you might have meant to break the loop with this value
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {break (fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50;} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                    +++++                                                                                                                                                                                                      +

error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3205:296
     |
3205 | ...0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} e...
     |       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
     |       |                                                                                                                                                                                                                             |
     |       |                                                                                                                                                                                                                             expected `()`, found `f64`
     |       expected this to be `()`
     |
help: consider using a semicolon here
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44};} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                       +
help: you might have meant to break the loop with this value
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {break (self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44;}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                 +++++                                                      +

error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3205:358
     |
3205 | ...e {if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} else {self.fRec44[0]} * ...
     |       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^^^^^^^^^^^^-
     |       |                                                                                                                                                                                                                                                                                                           |
     |       |                                                                                                                                                                                                                                                                                                           expected `()`, found `f64`
     |       expected this to be `()`
     |
help: you might have meant to break the loop with this value
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} else {break self.fRec44[0];} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                               +++++               +

error[E0614]: type `f64` cannot be dereferenced
    --> src/bin/vcf_wah_pedals.rs:3205:374
     |
3205 | ...0]) / fTemp44}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                          ^^^^^^^^^^^^^^^^
     |
help: parentheses are required to parse this as an expression
     |
3205 |             let mut fTemp76: F64 = if iSlow0 != 0 {fTemp38} else {(if iSlow2 != 0 {if iSlow28 != 0 {(fTemp73 * fTemp56 / fTemp60 + self.fRec69[1] * fTemp61 + 2.0 * (fTemp75 * self.fRec69[0] / fTemp58) + (1.0 - fTemp51 - 2.0 * fTemp54 * fTemp75) * fRec70 / (fTemp58 * F64::sqrt(fTemp55))) / fTemp50} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / fTemp44}} else {self.fRec44[0]}) * self.fRec43[0]};
     |                                                                   +                                                                                                                                                                                                                                                                                                                           +

error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3346:92
     |
3346 | ...0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} e...
     |       -----------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------------------------------------------------------------------------------------------------------------------------
     |       |                |
     |       |                expected `()`, found `f64`
     |       expected this to be `()`
     |
help: consider using a semicolon here
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))};} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
help: you might have meant to break the loop with this value
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {break ((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91;} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                     +++++                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +

error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3346:581
     |
3346 | ...0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} e...
     |       --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
     |       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     |       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         expected `()`, found `f64`
     |       expected this to be `()`
     |
help: consider using a semicolon here
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))};} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
help: you might have meant to break the loop with this value
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {break (self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30));}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +++++                                                                                                                +

error[E0308]: mismatched types
    --> src/bin/vcf_wah_pedals.rs:3346:701
     |
3346 | ...e {if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} else {self.fRec44[0]} * ...
     |       ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^^^^^^^^^^^^-
     |       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     |       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 expected `()`, found `f64`
     |       expected this to be `()`
     |
help: you might have meant to break the loop with this value
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} else {break self.fRec44[0];} * self.fRec43[0]};
     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +++++               +

error[E0614]: type `f64` cannot be dereferenced
    --> src/bin/vcf_wah_pedals.rs:3346:717
     |
3346 | ...0 - fSlow30))}} else {self.fRec44[0]} * self.fRec43[0]};
     |                                          ^^^^^^^^^^^^^^^^
     |
help: parentheses are required to parse this as an expression
     |
3346 |             let mut fTemp103: F64 = if iSlow0 != 0 {fTemp38} else {(if iSlow2 != 0 {if iSlow28 != 0 {((fTemp39 * fTemp99 + self.fRec72[1] * F64::sqrt(F64::max(0.0, fTemp100)) + ((1.0 - (fTemp98 + 2.0 * fTemp101 * fTemp102)) * fRec73 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp102)) + 2.0 * fTemp101 * self.fRec72[0]) / F64::sqrt(fTemp100)) * fTemp93 / fTemp97 + self.fRec69[1] * F64::sqrt(F64::max(0.0, fTemp94)) + ((1.0 - (fTemp92 + 2.0 * fTemp95 * fTemp96)) * fRec70 / F64::sqrt(1.0 - mydsp_faustpower2_f(fTemp96)) + 2.0 * fTemp95 * self.fRec69[0]) / F64::sqrt(fTemp94)) / fTemp91} else {(self.fRec67[2] + fTemp47 + self.fRec67[0]) / (fSlow32 + ((fTemp43 + 2.0 - fSlow30) / fTemp42 + 1.0 - fSlow30))}} else {self.fRec44[0]}) * self.fRec43[0]};
     |                                                                    +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +

Some errors have detailed explanations: E0308, E0614.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `faust-impulse-test` (bin "vcf_wah_pedals") due to 8 previous errors
make[1]: *** [Make.rust:126: ir/rust/vcf_wah_pedals.ir] Error 101
make[1]: Leaving directory '/home/crop/projects/rust/forks/faust/tests/impulse-tests'
make: *** [Makefile:365: rust] Error 2
```

**Comment by sletz** [comment]
I don't see it here.

rustc -V
rustc 1.81.0 (eeb90cda1 2024-09-04) (built from a source tarball)

macOS Monterey 12.7.6

**Comment by crop2000** [comment]
rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball)
Linux 6.1.108-rt40 #1-NixOS SMP PREEMPT_RT Wed Sep  4 11:25:05 UTC 2024 x86_64 GNU/Linux

**Comment by crop2000** [comment]
I think this PR is ready.
This change is fully backward compatible.
And tested with the impulse-tests.

**Comment by sletz** [comment]
Thanks. Testing here with [faust2portaudiorust](https://github.com/grame-cncm/faust/tree/master-dev/architecture/rust#faust2portaudiorust) tool, but I gets runtime error like: 

```
Faust Rust code running with Portaudio: sample-rate = 44100 buffer-size = 64
get_num_inputs: 1
get_num_outputs: 2
thread 'main' panicked at src/main.rs:227:11:
called `Result::unwrap()` on an `Err` value: InvalidChannelCount
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

so I guess the [current port audio architecture](https://github.com/grame-cncm/faust/blob/master-dev/architecture/rust/portaudio-float.rs),  which use a fixed `const CHANNELS: i32 = 2;` will have to be adapted.

Can you have a look ?

**Comment by crop2000** [comment]
yes i will have a look at the architecture files. unfortunately some of them are very outdated.

**Pull request merged**
