### PR TITLE
JAX Backend

### PR DESCRIPTION
**Pull request by DBraun**
I've been using this backend in several toy experiments with JAX. Before I polish and publish those experiments, I want to start the discussion of a PR for just the backend. I don't think anything here is broken, but I would welcome suggestions especially on `instructions_compiler.cpp`. The goal there was to build text like `return state, jnp.stack([_result0, _result1, _result2])`. Getting the PR merged soon would also help me get JAX integrated into DawDreamer.

Tagging @khiner in case you're interested too!

### CODE REVIEW

**Comment by sletz** [comment]
Can you first rebase this branch?

**Comment by DBraun** [comment]
I think it's already up to date with master-dev.

**Comment by sletz** [comment]
But the tree it not linear. It helps a lot to keep a linear tree (basically when you need to go back in time...), and we enforce that when merging PRs.  Can you rebase your branch before creating the PR?

**Comment by DBraun** [comment]
I tried but I think something's wrong.

**Comment by sletz** [comment]
What is wrong ?

**Comment by DBraun** [comment]
I don't think there's a problem with the rebase appveyor is showing a conflict in compiler/global.cpp.

**Comment by sletz** [comment]
Yes, this should be solved:
```
#ifdef JULIA_BUILD
    gJuliaVisitor = nullptr;  // Will be (possibly) allocated in Julia backend
<<<<<<< jax-backend
#endif

#ifdef JAX_BUILD
    gJAXVisitor = nullptr;    // Will be (possibly) allocated in JAX backend
=======
```

**Comment by khiner** [comment]
Very exciting! I should get a chance to look at this lawyer today/tomorrow. Wrt resolving the conflicts and such, looking through the activity on this PR I have a couple suggestions:
- It would make it a lot easier to review and merge if every commit of yours comes _after_ what’s currently on master-dev
- I saw you merged from master-dev into this branch, which is also confusing for review/merge back into master-dev.

What I usually do to get up-to-date with the upstream (Faust) target branch , is e.g. git pull —rebase upstream  master-dev. Then, resolve each conflict completely before each gif rebase —continue, until the rebase is complete. That would always put you in the nice situation where it’s just a simple sequence of new commits on top of Faust:master-dev, with no merge commits.

Since things are already a little jumbled up, however, I would suggest the following approach to get there:
- check out a new branch based off of the current Faust:master-dev (fresh, without any changes)
- separately cherry-pick each commit of yours from this PR’s branch onto that branch, making any cleanups and conflict resolutions completely after each cherry-pick
- make a new PR off of that branch (or push that branch up separately so it’s backed up and then force-push onto this branch)

**Comment by sletz** [comment]
I agree with @khiner here !

**Pull request closed without merging**
