### PR TITLE
Trill sensors support for faust2bela

### PR DESCRIPTION
**Pull request by PascalFaivre**
**Modification of the architecture/bela.cpp for adding the support of [Trill sensors](https://learn.bela.io/products/trill/about-trill/).**

Currently only BAR and SQUARE sensor type are supported. A maximum 8 sensors per type at the same time.
The parameters that can be used are: 
- position (x and y for the SQUARE type), 
- pressure 
- touch (Multitouch not supported)
For using, the approach is the same as digital and analog pin of the Bela.
The Metadata in the Faust Widget are  : 
TRILL:BAR_POS_n
TRILL:BAR_LVL_n
TRILL:BAR_TOUCH_n
TRILL:SQUARE_XPOS_n
TRILL:SQUARE_YPOS_n
TRILL:SQUARE_LVL_n
TRILL:SQUARE_TOUCH_n
where n is the index of the Trill sensor used
2 array (TrillBarAdress and TrillSquareAdress) allow to route the i2c addresses of the sensors index.

### CODE REVIEW

**Comment by sletz** [comment]
Thanks ! 
I did a bit of cleanup and reformatting and merged in "squash" (= unique commit) mode.  Can you check that it still works ? 
BTW are you https://dirigeant.societe.com/dirigeant/Pascal.FAIVRE-CUBIZOLLES.62087386.html ?

**Comment by PascalFaivre** [comment]
it does not compile the following 2 lines are in error :
738 static list<GUI*> GUI::fGuiList;
739 static ztimedmap GUI::gTimedZoneMap;

without 'static' is fonctional

**Comment by PascalFaivre** [comment]
yes it's me

**Comment by sletz** [comment]
Yes, stupid me ! Fixed in https://github.com/grame-cncm/faust/commit/731aa86a9b8c766c21e3a6dda547a7c5fa60726b

So beer and C++ ? ((-;

**Comment by PascalFaivre** [comment]
yes, among other things... I took a long break in development and by chance I discovered Faust. ;() forced to get back to it...

**Pull request closed without merging**
