### PR TITLE
CMake: set minor llvm version to zero in LLVM_xxx macro for recent LLVMs

### PR DESCRIPTION
**Pull request by jcelerier**
Minor CMake improvement so that we don't have to define LLVM_111, LLVM_112  etc...

### CODE REVIEW

**Comment by jcelerier** [comment]
wops, I messed my branches

**Comment by sletz** [comment]
I'm not sure to understand: 
- the PR was first about "WIP on a Libav sound reader " . Does this still is a WIP somewhere?
-  not it is renamed "CMake: set minor llvm version to zero in LLVM_xxx macro for recent LLVMs", should I merge it in this shape?

**Comment by sletz** [comment]
OK for you @dfober ?

**Comment by dfober** [comment]
it's probably going to break things for the previous versions (isn' it ?)
Maybe ensure compatibility with the previous behavior i.e. check LLVM version before setting to zero (?)

**Comment by sletz** [comment]
Tested and working on macOS from LLVM 8.0 to 11.0 (macports).

**Comment by jcelerier** [comment]
wops, sorry for not following back on this... yes, I remember testing various fake LLVM_VERSION numbers to make sure that it would not break old builds. 
(although, are there still people who build with very old LLVM versions such as LLVM 3 ? Even debian stable has LLVM 7)

**Comment by jcelerier** [comment]
regarding the libav thing, I messed my commits by force-pushing to master... I did put it in another branch and will make another PR when it's ready

**Comment by sletz** [comment]
> (although, are there still people who build with very old LLVM versions such as LLVM 3 ? Even debian stable has LLVM 7)

LLVM is not supported anymore below 8.0 version.

**Pull request merged**
