### PR TITLE
Faust2supercollider removal

### PR DESCRIPTION
**Pull request by olafklingt**
remove faust2supercollider because it fails silently because faust2sc doesn't exist anymore

### CODE REVIEW

**Comment by sletz** [comment]
I don't understand. `faust2supercollider` is still used in some use-cases. What is thisPR about ?

**Comment by olafklingt** [comment]
faust2supercollider depends on faust2sc which doesn't exist anymore. the UGens generated with faust2supercollider don't get a proper .sc file generated that describes the UGen.

**Comment by sletz** [comment]
Are you speaking of https://github.com/grame-cncm/faust/tree/master-dev/tools/faust2sc-1.0.0 ?

**Comment by olafklingt** [comment]
ah yes sorry i didn't see it

**Pull request closed without merging**
