### PR TITLE
New example - gameaudio/fire

### PR DESCRIPTION
**Pull request by mryndzionek**
Just a small example. Result of two evenings of experimentation. I think the result is pretty good taking into account the size and complexity of the file.

### CODE REVIEW

**Comment by sletz** [comment]
Nice ! Can you possibly add documentation the ways other examples (or at least some...) do ? (https://github.com/grame-cncm/faust/blob/master-dev/examples/gameaudio/bubble.dsp#L8)

**Comment by mryndzionek** [comment]
My example is not that 'parametrized', so I'm not sure what to document.

**Comment by mryndzionek** [comment]
Okay, I've refactored slightly, added on parameter and some docs.

**Comment by mryndzionek** [comment]
Okay, I've refactored slightly, added on parameter and some docs.

**Comment by sletz** [comment]
Thanks!

**Pull request merged**
