### PR TITLE
A number of Bela fixes

### PR DESCRIPTION
**Pull request by giuliomoro**
The polarity of digital inputs was wrong: a `0` meant `fMin + range`, a `1` meant `fMin`. Fixed.
The `BelaOSCUI` was not compiling. Fixed.
Added support for an `httpdUI`-based GUI to the architecture file and `faust2bela`.

### CODE REVIEW

**Comment by sletz** [comment]
Merge, thanks !

**Comment by giuliomoro** [comment]
thank you.
Do you routinely rebase the merges?

**Comment by sletz** [comment]
Yes, or we squash them.

**Comment by giuliomoro** [comment]
alright. In fact I had done a `git pull --rebase` just before creating the PR, hoping that that would help

**Pull request merged**
