### PR TITLE
faust2sndfile: add options to LINPUTS call, fix jack_midi_clear_buffer issue

### PR DESCRIPTION
**Pull request by LFSaw**
allows to run `faust2sndfile` with additional custom libraries:

```
faust2sndfile -I ../lib myDSP.dsp
```

### CODE REVIEW

**Comment by LFSaw** [comment]
related to https://github.com/grame-cncm/faust/issues/78

**Comment by sletz** [comment]
Thanks. Partly used in https://github.com/grame-cncm/faust/commit/c236d23526de80c410f8014d36bb803af1da18b8.

**Comment by LFSaw** [comment]
could you please elaborate if your commit fixes the issue i tried to fix?

**Comment by sletz** [comment]
I've just copied the `LINPUTS=$(faust $OPTIONS -uim "$f" | grep FAUST_INPUTS)` line in faust2sndfile.

**Comment by LFSaw** [comment]
Do I assume right that the issue of `jack_midi_reset_buffer` vs `jack_midi_clear_buffer` I fixed is related to jack1 vs jack2?

Also (and I know this is minor here but still want to ask) I am curious if there is any policy from grame that prevents you from modifying my commit and merging the PR into the master branch, preserving mixed authorship in the git version tree?

**Comment by sletz** [comment]
- yes, the is a JACK related issue that we will not merge (since the fix is not correct anyway)
- well 

> Do I assume right that the issue of `jack_midi_reset_buffer` vs `jack_midi_clear_buffer` I fixed is related to jack1 vs jack2?

- yes, the is a JACK related issue that we will not merge (since the fix is not correct anyway)

> 
> Also (and I know this is minor here but still want to ask) I am curious if there is any policy from grame that prevents you from modifying my commit and merging the PR into the master branch, preserving mixed authorship in the git version tree?

- well the fix was quite trivial. In this case I usually add the author name in the commit, I'v just forgotten this case... sorry for that.

**Comment by LFSaw** [comment]
> yes, the is a JACK related issue that we will not merge (since the fix is not correct anyway)

I'd like to use `faust2sndfile` on OSX but unfortunately it is relying on jack(2) (out of whatever reason...); this made the script compile for the jack version available through homebrew; how could I make this work for OSX (without compiling jack2 myself)?

> well the fix was quite trivial. In this case I usually add the author name in the commit, I'v just forgotten in this case... sorry for that.

nevermind 👍

**Comment by sletz** [comment]
Well ControlUI.h header is not needed in the first place AFAICS, fixed in: https://github.com/grame-cncm/faust/commit/cc637fc301d0b74bd3a1325f6cf40b8c461e817f

Can you test and report ? thanks.

**Pull request closed without merging**
