### PR TITLE
Rust code generation fixes and improvement

### LINKED ISSUE #334: Bugs in the Rust code generation
Rust code generation generates sometimes invalid code:

- `f32::fmod` does not exist anymore in the stdandard library
- `(0..4).rev()` (in some `compute` functions) actually iterates on 3, 2, 1, 0 whereas we actually want 4, 3, 2,1.

For instance in:
```
for j0 in (0..4).rev()  {
	self.fRec27[j0 as usize] = self.fRec27[(j0 - 1) as usize];
}
```
- too many parentheses lead to numerous warnings when compiling
- variable names should be snake case to prevent numerous warnings as well

### PR DESCRIPTION
**Pull request by programLyrique**
Closes #334 

- the reverse iteration is fixed: `(0..4).rev()` is replaced by the correct version `4..0`
- `fmod`and `fmodf`:  I use the [libm create](https://docs.rs/libm/0.1.4/libm/) so it adds a dependency. 
- in addition, uses modern rust error catching in the architecture file. The `try!` macro becomes the `?` operator. This new operator is used since 2016.
- snake case: I have not fixed that yet. For now, there is `#![allow(non_snake_case)]` in the architecture file, which hides the related warnings.

### CODE REVIEW

**Comment by sletz** [comment]
The PR is a bit shaky. Can you possibly make it appear as "rebased" ? That is your changed would be on top of the branch. Or just send me the separated commits ? (which should be in a small number yes?). Thanks.

**Comment by sletz** [comment]
Or do I just ned to apply this diff yes ? https://patch-diff.githubusercontent.com/raw/grame-cncm/faust/pull/338.diff

**Comment by programLyrique** [comment]
My commits appear at the end, in chronological order and there are 3 (plus the automatic merge).
Is it the last merge which is problematic?
In that case, is it possible to apply only up to commit 6c8b889 ?

I am going to try to rebase...

**Comment by sletz** [comment]
I see a change in `faust2portaudiorust`. I guess the same would have to be done in `faust2jackrust` ?

**Comment by programLyrique** [comment]
Yes, indeed. I am going to correct it.

As for the rebase, I think it is possible to do it from upstream on the pull request: https://help.github.com/en/articles/about-pull-request-merges

I also just removed the merge of upstream I had on my branch.

**Comment by sletz** [comment]
I finally did 3 `git cherry-pick`, see: https://github.com/grame-cncm/faust/commits/master-dev

Should be OK, please confirm.

**Comment by sletz** [comment]
Hum, trying, I see this error:

```
   Compiling freeverb-rust v0.1.0 (/Documents/faust-github-faust2/examples/reverb/freeverb-rust)
error: expected expression, found reserved keyword `try`
   --> src/main.rs:832:14
    |
832 |     let pa = try!(pa::PortAudio::new());
    |              ^^^ expected expression

warning: unused import: `std::io`
  --> src/main.rs:26:5

```

**Comment by programLyrique** [comment]
I think I removed all the `try!` to replace by the new instruction `?` so there should not be such errors. I am going to check and if they are still there, I will push a new commit.

**Comment by sletz** [comment]
cherry-picked https://github.com/grame-cncm/faust/commit/88dc9f2603fe51cfb2e3865863f0e584d5359d1e

And fixed another issue when using tables: 
https://github.com/grame-cncm/faust/commit/b0a9726b1cb7dd6c63e3aeaae063ef0cc64f6c03

Now working.

**Pull request closed without merging**
