### PR TITLE
added buttons and dynamic memory management

### PR DESCRIPTION
**Pull request by pingdynasty**
Brings the OWL architecture file up to date and adds support for Stéphane's latest `dsp_memory_manager`

### CODE REVIEW

**Comment by sletz** [comment]
Seems like the following code in incorrect (you are destroying the fDSP object "twice"..)

 ~FaustPatch(){
 	mem.destroy(fDSP);
 	delete fDSP;
       }

If you want to use the custom allocator for the mysdsp object memory, then C++ placement new should be used, that is:

fDSP = new (mem.allocate(sizeof(mydsp)) mydsp(); in  FaustPatch() constructor

and

fDSP->~mydsp() (even if ~mydsp() does nothing but you can see the point...)
mem.destroy(fDSP);

**Comment by pingdynasty** [comment]
destroy twice: correct, I'll fix it.

placement new: Since the memory allocator is using `new`/`delete` I am using the same mechanism in the patch ctor.

I'll replace this with a better PR.

**Comment by sletz** [comment]
If you use fDSP = mydsp();  then the standard C++ operator new is called.. you don't control it. Using placement new with your custom allocation then you fully control the allocation/destroy steps...

**Comment by sletz** [comment]
You can just update/Correct the PR with a new commit I guess...., I can possibly using "smash merge" to have ann intermediate commits in a unique big one.

**Comment by sletz** [comment]
Ok now I read the comment "Simple heap based memory manager * Uses overloaded new/delete operators on OWL hardware.", so OK for the contractor part then...

**Comment by pingdynasty** [comment]
I've added placement new as you suggested (separate PR). It amounts to the same thing atm, but if we change the memory manager in the future it will be useful to have the dsp object allocated in the same way.

**Pull request closed without merging**
