### PR TITLE
Daisy patch and custom hardware - support 4 ins/outs

### PR DESCRIPTION
**Pull request by sc3sc3**
These are edits by different people on discord: sletz, makingsoundmachines, Along the Arc

Compilation of the resulting ex_faust.cpp fails: see attached ex_faust_cpp.txt( renamed, github doesn't supporting attaching cpp filees ) and error.txt
[ex_faust_cpp.txt](https://github.com/grame-cncm/faust/files/6604945/ex_faust_cpp.txt)
[error.txt](https://github.com/grame-cncm/faust/files/6604947/error.txt)

### CODE REVIEW

**Comment by sletz** [comment]
I reworked the code here https://github.com/grame-cncm/faust/commit/c5d5542847a86e4f567613312e8c75d2b24dc4a7, can you test and report?

**Comment by sc3sc3** [comment]
Thank you!
Yes, I will test and report back today.

**Comment by sc3sc3** [comment]
following errors occur, ex_faust_cpp.txt is attached:


ex_faust.cpp: In function 'int main()':
ex_faust.cpp:9797:8: error: 'class daisy::DaisyPatch' has no member named 'Configure'
 9797 |     hw.Configure();
      |        ^~~~~~~~~
ex_faust.cpp:9818:71: error: no matching function for call to 'DaisyControlUI::DaisyControlUI(daisy::DaisyPatch*, int)'
 9818 |     control_UI = new DaisyControlUI(&hw, MY_SAMPLE_RATE/MY_BUFFER_SIZE);
      |                                                                       ^
ex_faust.cpp:1035:9: note: candidate: 'DaisyControlUI::DaisyControlUI(daisy::DaisySeed*, int)'
 1035 |         DaisyControlUI(daisy::DaisySeed* seed, int rate)
      |         ^~~~~~~~~~~~~~
ex_faust.cpp:1035:42: note:   no known conversion for argument 1 from 'daisy::DaisyPatch*' to 'daisy::DaisySeed*'
 1035 |         DaisyControlUI(daisy::DaisySeed* seed, int rate)
      |                        ~~~~~~~~~~~~~~~~~~^~~~
ex_faust.cpp:916:7: note: candidate: 'DaisyControlUI::DaisyControlUI(const DaisyControlUI&)'
  916 | class DaisyControlUI : public GenericUI
      |       ^~~~~~~~~~~~~~
ex_faust.cpp:916:7: note:   candidate expects 1 argument, 2 provided
ex_faust.cpp:916:7: note: candidate: 'DaisyControlUI::DaisyControlUI(DaisyControlUI&&)'
ex_faust.cpp:916:7: note:   candidate expects 1 argument, 2 provided
make: *** [/home/interlichtspielhaus/git/libDaisy//core/Makefile:224: build/ex_faust.o] Error 1
[ex_faust_cpp.txt](https://github.com/grame-cncm/faust/files/6607806/ex_faust_cpp.txt)

**Comment by sletz** [comment]
Another try with https://github.com/grame-cncm/faust/commit/ad4f1160c55c14bcf7da84132e9f8502abab2903, can you test and report?

**Comment by sc3sc3** [comment]
That works for me. The 4 four control knobs work and the 4 outs function.
Thank you !!

**Pull request closed without merging**
